# Default values for FANZ Unified Ecosystem
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  registry: ghcr.io
  repository: fanzceo
  pullPolicy: IfNotPresent
  imagePullSecrets: []

# Image configuration
image:
  tag: latest

# Services configuration
services:
  api:
    enabled: true
    name: fanz-api
    replicaCount: 3
    port: 3000
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70

  blockchain-node:
    enabled: true
    name: fanz-blockchain
    replicaCount: 2
    port: 8545
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi

  metaverse-server:
    enabled: true
    name: fanz-metaverse
    replicaCount: 2
    port: 8080
    resources:
      requests:
        cpu: 2000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 8Gi

  quantum-processor:
    enabled: false
    name: fanz-quantum
    replicaCount: 1
    port: 9000
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 8000m
        memory: 16Gi

  auto-scaler:
    enabled: true
    name: fanz-autoscaler
    replicaCount: 1
    port: 8081
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  game-server:
    enabled: true
    name: fanz-game
    replicaCount: 2
    port: 7777
    resources:
      requests:
        cpu: 1500m
        memory: 2Gi
      limits:
        cpu: 3000m
        memory: 4Gi

# Database configuration
databases:
  postgres:
    enabled: true
    host: postgres
    port: 5432
    database: fanz
    username: fanzuser
    existingSecret: fanz-db-secret

  mongodb:
    enabled: true
    host: mongodb
    port: 27017
    database: fanz
    existingSecret: fanz-mongo-secret

  redis:
    enabled: true
    host: redis
    port: 6379
    existingSecret: fanz-redis-secret

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: api.fanz.eco
      paths:
        - path: /
          pathType: Prefix
          service: fanz-api
    - host: metaverse.fanz.eco
      paths:
        - path: /
          pathType: Prefix
          service: fanz-metaverse
  tls:
    - secretName: fanz-tls
      hosts:
        - api.fanz.eco
        - metaverse.fanz.eco

# Monitoring
monitoring:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  grafana:
    enabled: true

# Logging
logging:
  fluentd:
    enabled: true
  elasticsearch:
    enabled: true

# Security
security:
  podSecurityPolicy:
    enabled: true
  networkPolicy:
    enabled: true

# Service Mesh
serviceMesh:
  istio:
    enabled: false
  linkerd:
    enabled: false
