services:
  fanz-app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - FANZ_ENV=${FANZ_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - fanz-db
    restart: unless-stopped

  fanz-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fanz_dev
      POSTGRES_USER: fanz
      POSTGRES_PASSWORD: fanz_dev_password
    ports:
      - "5432:5432"
    volumes:
      - fanz_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  fanz_db_data:
