services:
  # Core Infrastructure
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: fanz_ecosystem
      POSTGRES_USER: fanz_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-prod_password_secure_2024}
    ports:
      - "5432:5432"
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fanz_user -d fanz_ecosystem"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # PRODUCTION FANZ PLATFORM APPLICATIONS

  # Real FanzLanding Platform (Node.js/React App) - PRODUCTION MODE
  fanz-landing:
    image: node:20-alpine
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://fanz_user:${DB_PASSWORD:-prod_password_secure_2024}@postgres:5432/fanz_ecosystem
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=${SESSION_SECRET:-fanz_session_secret_prod_2024_secure}
      - JWT_SECRET=${JWT_SECRET:-fanz_jwt_secret_prod_2024_secure}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-fanz_encryption_prod_key_32bytes_secure}
      - APP_NAME=FanzLanding
      - APP_URL=http://localhost:3000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3030,http://localhost:8090
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /Users/joshuastone/Documents/GitHub/FanzLanding:/app
      - /app/node_modules
    working_dir: /app
    command: ["sh", "-c", "npm install --legacy-peer-deps && npm run build && npm start"]
    restart: unless-stopped

  # Real FanzDash Platform (Admin Control Center) - PRODUCTION MODE
  fanzdash:
    image: node:20-alpine
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
      - PORT=3030
      - DATABASE_URL=postgresql://fanz_user:${DB_PASSWORD:-prod_password_secure_2024}@postgres:5432/fanz_ecosystem
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=${SESSION_SECRET:-fanz_session_secret_prod_2024_secure}
      - JWT_SECRET=${JWT_SECRET:-fanz_jwt_secret_prod_2024_secure}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-fanz_encryption_prod_key_32bytes_secure}
      - APP_NAME=FanzDash
      - APP_URL=http://localhost:3030
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3030,http://localhost:8090
      - ADMIN_MODE=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /Users/joshuastone/Documents/GitHub/FanzDash:/app
      - /app/node_modules
    working_dir: /app
    command: ["sh", "-c", "npm install --legacy-peer-deps && npm run build && npm start"]
    restart: unless-stopped

  # API Gateway (Enhanced with Security Fixes) - PRODUCTION MODE
  api-gateway:
    build:
      context: .
      dockerfile_inline: |
        FROM node:20-alpine
        RUN apk add --no-cache python3 make g++
        WORKDIR /app
        COPY api-gateway/ ./
        RUN npm install --legacy-peer-deps
        RUN npm run build
        EXPOSE 8090
        CMD ["npm", "start"]
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production
      - PORT=8090
      - DATABASE_URL=postgresql://fanz_user:${DB_PASSWORD:-prod_password_secure_2024}@postgres:5432/fanz_ecosystem
      - REDIS_URL=redis://redis:6379
      - FANZ_LANDING_URL=http://fanz-landing:3000
      - FANZ_DASH_URL=http://fanzdash:3030
    depends_on:
      - postgres
      - redis
      - fanz-landing
      - fanzdash
    restart: unless-stopped

  # Real Platform Applications (Production Stubs)
  boyfanz:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - /Users/joshuastone/Documents/GitHub/FANZ-Unified-Ecosystem/stubs/boyfanz.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - postgres
      - redis
    labels:
      - "platform.status=production"
      - "platform.mode=live"

  girlfanz:
    image: nginx:alpine
    ports:
      - "3002:80"
    volumes:
      - /Users/joshuastone/Documents/GitHub/FANZ-Unified-Ecosystem/stubs/girlfanz.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - postgres
      - redis
    labels:
      - "platform.status=production"
      - "platform.mode=live"

  pupfanz:
    image: nginx:alpine
    ports:
      - "3003:80"
    volumes:
      - /Users/joshuastone/Documents/GitHub/FANZ-Unified-Ecosystem/stubs/pupfanz.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - postgres
      - redis
    labels:
      - "platform.status=production"
      - "platform.mode=live"

volumes:
  postgres_data:
  redis_data: