# 🚀 FANZ Unified Ecosystem - pnpm Workspace Configuration
# Manages 100+ packages across platform clusters, specialized systems, and microservices

packages:
  # 🌈 Platform Clusters (9 clusters)
  - "platform-clusters/fanzlab"
  - "platform-clusters/boyfanz"
  - "platform-clusters/girlfanz"
  - "platform-clusters/daddyfanz"
  - "platform-clusters/pupfanz"
  - "platform-clusters/taboofanz"
  - "platform-clusters/transfanz"
  - "platform-clusters/cougarfanz"
  - "platform-clusters/fanzcock"
  - "platform-clusters/shared/**"

  # 🔧 Specialized Systems (7 core systems)
  - "specialized-systems/creator-crm"
  - "specialized-systems/biolinkhub"
  - "specialized-systems/chatsphere"
  - "specialized-systems/mediacore"
  - "specialized-systems/fanz-social-fanz-social"
  - "specialized-systems/fanzgpt"
  - "specialized-systems/fanzshield"

  # ⚡ Microservices (100+ services)
  - "microservices/api-gateway"
  - "microservices/user-service"
  - "microservices/content-service"
  - "microservices/payment-service"
  - "microservices/fanzfluence-service"
  - "microservices/fanzversity-service"
  - "microservices/fanzmetaverse-service"
  - "microservices/gamification-service"
  - "microservices/merchandise-service"
  - "microservices/monitoring-service"
  - "microservices/security-service"
  - "microservices/storage-service"
  - "microservices/explore-service"
  - "microservices/advanced-ai-service"
  - "microservices/advanced-content-moderation"
  - "microservices/advanced-mobile-features"
  - "microservices/ai-assistant-service"
  - "microservices/ai-chatbot-service"
  - "microservices/ai-voice-cloning-service"
  - "microservices/analytics-service"
  - "microservices/authentication-service"
  - "microservices/broadcasting-service"
  - "microservices/collaboration-service"
  - "microservices/compliance-service"
  - "microservices/content-filtering-service"
  - "microservices/content-protection-service"
  - "microservices/costar-service"
  - "microservices/crypto-payment-service"
  - "microservices/education-service"
  - "microservices/external-storage-service"
  - "microservices/fan-relationship-service"
  - "microservices/immersive-experience-service"
  - "microservices/link-in-bio-service"
  - "microservices/live-streaming-service"
  - "microservices/nft-marketplace-service"
  - "microservices/notification-service"
  - "microservices/podcast-service"
  - "microservices/real-time-notification-service"
  - "microservices/sms-service"
  - "microservices/websocket-service"
  - "microservices/predictive-analytics-service"
  - "microservices/recommendation-engine"
  - "microservices/rate-limiting-service"
  - "microservices/seo-automation-service"
  - "microservices/server-management-service"
  - "microservices/service-integration-service"
  - "microservices/ssh-ftp-service"
  - "microservices/short-video-service"
  - "microservices/video-studio-service"
  - "microservices/virtual-cards-service"
  - "microservices/social-media-tools-service"
  - "microservices/user-tagging-service"

  # 💰 FanzFinance OS Services (per your rules)
  - "fanzfinance-os/core-ledger-service"
  - "fanzfinance-os/transaction-processing-engine"
  - "fanzfinance-os/transaction-controller"
  - "fanzfinance-os/financial-reports-controller"
  - "fanzfinance-os/ai-financial-advisor"

  # 📦 Shared Packages
  - "packages/ui"
  - "packages/shared"
  - "packages/config"
  - "packages/eslint-config"
  - "packages/tsconfig"
  - "packages/themes"

  # 🤖 AI Services
  - "ai-content-intelligence"
  - "ai/**"

  # 🛡️ Security Services
  - "security/**"

  # ⚙️ Infrastructure
  - "infrastructure/**"

  # 📚 Tools and Utilities
  - "tools/**"

  # 🎭 Blockchain and Web3
  - "blockchain/**"

  # 🌌 Metaverse Services
  - "metaverse/**"

  # 🧪 Testing and Quality
  - "tests/**"

  # Existing services to maintain compatibility
  - "auth-service"
  - "backend"
  - "frontend"