# FANZ Cross-Platform Ad System - PNPM Workspace Configuration
# Monorepo workspace for all FANZ ad system packages

packages:
  # Core packages
  - "packages/*"
  
  # Applications
  - "apps/*"
  
  # Services  
  - "services/*"
  
  # OpenAPI specification
  - "openapi"

# Shared dependencies that should be hoisted to workspace root
shared-workspace-lockfile: true

# Package installation settings
prefer-workspace-packages: true

# Peer dependency settings
auto-install-peers: true
dedupe-peer-dependents: true

# Catalog configuration for shared package versions
catalog:
  react: '18.3.1'
  react-dom: '18.3.1'
  '@types/react': '18.3.11'
  '@types/react-dom': '18.3.1'
  typescript: '5.6.3'
  eslint: '9.15.0'
  prettier: '3.3.3'
  tailwindcss: '3.4.14'
  next: '14.2.16'
  express: '4.21.1'
  cors: '2.8.5'
  helmet: '8.0.0'
  joi: '17.13.3'
  winston: '3.17.0'
  pg: '8.13.1'
  prisma: '6.1.0'

# Resolution overrides for security and consistency  
resolutions:
  # Security updates
  "node-fetch": "^3.3.2"
  "semver": "^7.6.0"
  "tough-cookie": "^4.1.3"
  "lodash": "^4.17.21"
  "axios": "^1.7.7"
  
  # React consistency across packages
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "@types/react": "^18.3.11"
  "@types/react-dom": "^18.3.1"
  
  # TypeScript consistency
  "typescript": "^5.6.3"
  
  # Next.js consistency
  "next": "^14.2.16"
  
  # Adult content compliance
  "content-security-policy": "^0.7.0"
  "helmet": "^8.0.0"

# NPM configuration
npmrc: |
  # Faster installs
  prefer-offline=true
  
  # Security
  audit-level=moderate
  fund=false
  
  # Adult-friendly package registries only
  # Block any packages from prohibited payment processors
  @stripe:registry=https://registry.npmjs.org/
  @paypal:registry=https://registry.npmjs.org/
  
  # Logging
  loglevel=warn