{{- if .Values.services.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.api.name }}
  labels:
    {{- include "fanz-ecosystem.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.services.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.services.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.api.name }}
        {{- include "fanz-ecosystem.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.services.api.name }}
        image: {{ .Values.global.registry }}/{{ .Values.global.repository }}/fanz-api:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.pullPolicy }}
        ports:
        - containerPort: {{ .Values.services.api.port }}
          name: http
        env:
        - name: PORT
          value: "{{ .Values.services.api.port }}"
        - name: NODE_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.databases.postgres.existingSecret }}
              key: url
        resources:
          {{- toYaml .Values.services.api.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.api.name }}
  labels:
    {{- include "fanz-ecosystem.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.api.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.services.api.name }}
{{- if .Values.services.api.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.services.api.name }}
  labels:
    {{- include "fanz-ecosystem.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.services.api.name }}
  minReplicas: {{ .Values.services.api.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.api.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.services.api.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
