[tools]
# Pin runtime versions for consistency
node = "20.10.0"
pnpm = "8.10.5"
python = "3.11.6"
golang = "1.21.4"
rust = "1.74.1"

[settings]
experimental = true
trusted-config = true

[tasks]
# Development lifecycle
dev = "pnpm run dev"
build = "pnpm run build"
test = "pnpm run test"
lint = "pnpm run lint"
format = "pnpm run format"

# Quality gates
check = [
  "pnpm run lint",
  "pnpm run typecheck", 
  "pnpm run test",
  "pnpm run audit"
]

# Deployment
deploy-dev = "./scripts/deploy.sh development"
deploy-staging = "./scripts/deploy.sh staging"
deploy-prod = "./scripts/deploy.sh production"

# Monitoring
health-check = "./scripts/health-check.sh"
monitoring = "./scripts/setup-monitoring.sh"

[env]
# Development environment
NODE_ENV = "development"
LOG_LEVEL = "debug"
FANZ_ENVIRONMENT = "local"

# Adult-friendly payment processing (NO Stripe/PayPal)
PAYMENT_PROCESSOR = "ccbill"
ADULT_CONTENT_MODE = "true"
COMPLIANCE_MODE = "strict"

# Security defaults
TLS_VERSION = "1.3"
ENCRYPTION_STANDARD = "aes-256"
AUTH_MODE = "zero-trust"

# FANZ branding
PLATFORM_BRAND = "FANZ"
ECOSYSTEM_NAME = "FANZ Unlimited Network"