apiVersion: v1
kind: Namespace
metadata:
  name: fanz-production
  labels:
    name: fanz-production
    app.kubernetes.io/name: fanz
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: fanz-ecosystem
    app.kubernetes.io/managed-by: kubectl
    # Pod Security Standards
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    description: "FANZ Unified Ecosystem production namespace"
    contact: "devops@fanz.network"
    created-by: "FANZ DevOps Team"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fanz-resource-quota
  namespace: fanz-production
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Gi
    limits.cpu: "200"
    limits.memory: 400Gi
    persistentvolumeclaims: "50"
    pods: "100"
    services: "20"
    secrets: "50"
    configmaps: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: fanz-limit-range
  namespace: fanz-production
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container