apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: amp-error-rate
  namespace: default
  labels:
    app.kubernetes.io/part-of: fanz-warp-directive
spec:
  args:
  - name: svc
    value: golden-api
  metrics:
  - name: error-rate
    interval: 30s
    successCondition: result[0] < 0.05
    failureLimit: 3
    count: 5
    provider:
      prometheus:
        address: http://prometheus.observability.svc.cluster.local:9090
        query: |
          sum(rate(http_requests_total{service="{{args.svc}}",status=~"5.."}[5m])) / 
          sum(rate(http_requests_total{service="{{args.svc}}"}[5m]))
  - name: response-time-p99
    interval: 30s  
    successCondition: result[0] < 1.0
    failureLimit: 3
    count: 5
    provider:
      prometheus:
        address: http://prometheus.observability.svc.cluster.local:9090
        query: |
          histogram_quantile(0.99, 
            sum(rate(http_request_duration_seconds_bucket{service="{{args.svc}}"}[5m])) by (le)
          )