name: daddyfanz
region: nyc

services:
  - name: web
    github:
      repo: your-username/daddyfanz
      branch: main
      deploy_on_push: true
    
    build_command: npm install && npm run build
    run_command: npm start
    
    environment_slug: node-js
    
    instance_count: 1
    instance_size_slug: professional-xs
    
    http_port: 5000
    
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PUBLIC_OBJECT_SEARCH_PATHS
        scope: RUN_TIME
        type: SECRET
      - key: PRIVATE_OBJECT_DIR
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGIN
        value: https://daddiesfanz.com,https://fanz.daddiesfanz.com
      - key: PORT
        value: "5000"

    routes:
      - path: /
        preserve_path_prefix: true

databases:
  - name: daddyfanz-db
    engine: PG
    version: "15"
    production: true
    cluster_name: daddyfanz-cluster

domains:
  - domain: daddiesfanz.com
    type: PRIMARY
  - domain: fanz.daddiesfanz.com
    type: ALIAS
