# 🛡️ FANZ Kubernetes Security Policy
# Enforces strict security controls across all Kubernetes resources
apiVersion: v1
kind: ConfigMap
metadata:
  name: fanz-k8s-security-policy
  namespace: fanz-system
data:
  security-requirements.yaml: |
    # Security Requirements for FANZ Kubernetes Resources
    
    # 1. Container Security
    containers:
      - runAsNonRoot: true
      - readOnlyRootFilesystem: true
      - allowPrivilegeEscalation: false
      - capabilities:
          drop: ["ALL"]
      - seccompProfile:
          type: RuntimeDefault
      
    # 2. Pod Security
    pods:
      - securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
      - automountServiceAccountToken: false
      - hostNetwork: false
      - hostPID: false
      - hostIPC: false
      
    # 3. Network Security
    network:
      - networkPolicies: required
      - defaultDeny: true
      - egressControl: strict
      
    # 4. Resource Management
    resources:
      - limits: required
      - requests: required
      - ephemeralStorage: limited
      
    # 5. Image Security
    images:
      - digestPinning: required
      - vulnerabilityScanning: required
      - trustedRegistries: enforced
