---
deployment:
  tasks:
    - export DEPLOYPATH=/home/boyfanz/boyfanz
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH && /usr/local/bin/node /opt/cpanel/ea-nodejs22/bin/npm install --production
    - cd $DEPLOYPATH && /usr/local/bin/node /opt/cpanel/ea-nodejs22/bin/npm run build
