version: '3.8'

services:
  fanz-ai-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-development_secret}
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - fanz-ai-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - fanz-ai-network
    command: redis-server --appendonly yes

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - fanz-ai-network

networks:
  fanz-ai-network:
    driver: bridge

volumes:
  redis_data: